apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dadatachart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dadatachart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "hyhyena/hello:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: 8080